# config/meta.yml
meta_title: "Volunteasy "
meta_description: "Help out here and now"
meta_image: "logo_big.png" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
